arantes:
  client:
    address:
      url: http://localhost:8082/address

spring:
  application:
    name: Template Java - Hexagonal
  data:
    mongodb:
      uri: mongodb://localhost:27017/hexagonal
